// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const start = performance.now();

    const { data } = await supabase.auth.getSession();

    const sessionTime = performance.now();

    const token = data.session?.access_token;

    console.log("[Supabase Auth] getSession:", {
      ms: Math.round(sessionTime - start),
      hasSession: Boolean(data.session),
    });

  console.log(
    "[Supabase Auth]",
    token
      ? `Token present: length=${token.length}, parts=${token.split(".").length}`
     : "No access token"
  )
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
